CREATE DATABASE KOKILAN1005;
USE KOKILAN1005;
CREATE TABLE department (
    Department_ID INT PRIMARY KEY,
    Department_Name VARCHAR(20),
    HOD VARCHAR(20)
);
DESC department;
SELECT*FROM KOKILAN1005;
